// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmibilcrqnxbjryfqoap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtaWJpbGNycW54YmpyeWZxb2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Mjg5NDQsImV4cCI6MjA1ODQwNDk0NH0.7d7NDs5otv0GS5KzB_ZLu4i7xD3ynkcvoojNwEhk95E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);